# Generated by Django 3.0.6 on 2020-06-25 09:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('release', models.IntegerField()),
                ('playTime', models.IntegerField()),
                ('genre', models.TextField()),
                ('albumArt', models.ImageField(blank=True, upload_to='image')),
                ('desription', models.TextField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
