# Generated by Django 3.0.6 on 2020-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('recommend', models.CharField(choices=[('good', '좋아요'), ('bad', '싫어요')], max_length=5)),
            ],
        ),
    ]
