# Generated by Django 3.0.6 on 2020-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youTubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=20)),
                ('preference', models.IntegerField()),
                ('live', models.BooleanField()),
                ('subscribers', models.IntegerField()),
                ('link1', models.TextField()),
                ('link2', models.TextField()),
                ('link3', models.TextField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
