# Generated by Django 3.0.6 on 2020-05-23 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makePage', '0003_auto_20200519_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
