# Generated by Django 3.0.6 on 2020-05-30 03:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singerName', models.CharField(default='가수이름을 입력해주세요', max_length=100)),
                ('favSongName1', models.CharField(default='곡명을 입력해주세요', max_length=50)),
                ('whyFavSinger', models.TextField(default='애정 이유는 뭔가요?')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
