# Generated by Django 3.0.6 on 2020-06-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('memberId', models.IntegerField(primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=127)),
                ('home', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('memberId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.members')),
            ],
        ),
    ]
