# Generated by Django 3.0.6 on 2020-06-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200630_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='orderId',
        ),
    ]
