# Generated by Django 3.0.6 on 2020-06-29 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumGallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myalbum',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='myalbum',
            name='release',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
